---
parent: null
name: Base
keys:
    "a": "ေ"
    "b": "ဘ"
    "c": "ခ"
    "d": "ိ"
    "e": "န"
    "f": "်"
    "g": "ါ"
    "h": "့"
    "i": "င"
    "j": "ြ"
    "k": "ု"
    "l": "ူ"
    "m": "ာ"
    "n": "ည"
    "o": "သ"
    "p": "စ"
    "q": "ဆ"
    "r": "မ"
    "s": "ျ"
    "t": "အ"
    "u": "က"
    "v": "လ"
    "w": "တ"
    "x": "ထ"
    "y": "ပ"
    "z": "ဖ"
    "1": "၁"
    "2": "၂"
    "3": "၃"
    "4": "၄"
    "5": "၅"
    "6": "၆"
    "7": "၇"
    "8": "၈"
    "9": "၉"
    "0": "၀"
    "grave": "ၐ"
    "dash": "-"
    "equals": "="
    "openbrace": "ဟ"
    "closebrace": "ဩ"
    "backslash": "၏"
    "semicolon": "း"
    "singlequote": "'"
    "comma": ","
    "period": "."
    "slack": "/"
    "s_a": "ဗ"
    "s_b": "ယ"
    "s_c": "ဃ"
    "s_d": "ီ"
    "s_e": "ဣ"
    "s_f": "္"
    "s_g": "ွ"
    "s_h": "ံ"
    "s_i": "၍"
    "s_j": "ဲ"
    "s_k": "ဒ"
    "s_l": "ဓ"
    "s_m": "ဦ"
    "s_n": "ဉ"
    "s_o": "ဿ"
    "s_p": "ဏ"
    "s_q": "ဈ"
    "s_r": "၎"
    "s_s": "ှ"
    "s_t": "ဤ"
    "s_u": "ဥ"
    "s_v": "ဠ"
    "s_w": "ဝ"
    "s_x": "ဌ"
    "s_y": "၌"
    "s_z": "ဇ"
    "s_1": "ဍ"
    "s_2": "ၒ"
    "s_3": "ဋ"
    "s_4": "ၓ"
    "s_5": "ၔ"
    "s_6": "ၕ"
    "s_7": "ရ"
    "s_8": "*"
    "s_9": "("
    "s_0": ")"
    "s_grave": "ဎ"
    "s_dash": "_"
    "s_equals": "+"
    "s_openbrace": "ဧ"
    "s_closebrace": "ဪ"
    "s_backslash": "ၑ"
    "s_semicolon": "ဂ"
    "s_singlequote": '"'
    "s_comma": "<"
    "s_period": ">"
    "s_slack": "?"